// This file is generated by Velite

export { default as posts } from './posts.json' with { type: 'json' }
export { default as authors } from './authors.json' with { type: 'json' }
export { default as pages } from './pages.json' with { type: 'json' }