// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Post = Collections['posts']['schema']['_output']
export declare const posts: Post[]

export type Author = Collections['authors']['schema']['_output']
export declare const authors: Author[]

export type Page = Collections['pages']['schema']['_output']
export declare const pages: Page[]
