apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vielang.fullname" . }}-secrets
  labels:
    {{- include "vielang.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: "postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "vielang.postgresHost" . }}:5432/{{ .Values.postgresql.auth.database }}"
  jwt-secret: {{ .Values.config.jwtSecret | quote }}
